networks:
  internal_bridge: # docker network create --driver bridge --opt "com.docker.network.bridge.bind_iface=eth0" internal_bridge
    external: true

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Toronto
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    networks:
      - internal_bridge
    ports:
      - 28083:8083
    volumes:
      - /root/docker/calibre_web/data:/config
      - /root/docker/calibre_web/library:/books
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    #security_opt:
    #  - seccomp:unconfined #optional
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Toronto
    networks:
      - internal_bridge
    ports:
      #- 8080:8080
      - 28181:8181
      #- 8081:8081
    volumes:
      - /root/docker/calibre/config:/config
      - /root/docker/calibre_web/library:/books
    restart: unless-stopped
