networks:
  macvlan_internal:
    external: true
  macvlan_external:
    external: true

services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    networks:
      - macvlan_external
    environment:
      TUNNEL_TOKEN: ${TOKEN}
      TUNNEL_DNS_UPSTREAM: ${DOH_URL},${DOH_URL_BACKUP}
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_ADDRESS: 0.0.0.0
    volumes:
      - ${DOCKER_VOLUME_DIR}/cloudflared:/etc/cloudflared

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    depends_on:
      - cloudflared-tunnel
    networks:
      - macvlan_internal
    volumes:
      - ${DOCKER_VOLUME_DIR}/nginx-proxy-manager/data:/data
      - ${DOCKER_VOLUME_DIR}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
