networks:
  macvlan_internal:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.1
  macvlan_dmz:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.10.20.0/24
          gateway: 10.10.20.1

services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TOKEN}
      TUNNEL_DNS_UPSTREAM: ${DOH_URL},${DOH_URL_BACKUP}
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_ADDRESS: 0.0.0.0
    volumes:
      - ${DOCKER_VOLUME_DIR}/cloudflared:/etc/cloudflared
    networks:
      macvlan_dmz:
        ipv4_address: 10.10.20.2

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    depends_on:
      - cloudflared-tunnel
    ports:
      - 181:81
    volumes:
      - ${DOCKER_VOLUME_DIR}/nginx-proxy-manager/data:/data
      - ${DOCKER_VOLUME_DIR}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      macvlan_internal:
        ipv4_address: 10.0.10.2
